// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using kz.Models;

#nullable disable

namespace kz.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20230922153533_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("kz.Models.Article", b =>
                {
                    b.Property<string>("TabelCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ArticleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArticleType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DayTime")
                        .HasColumnType("int");

                    b.Property<int?>("HourTime")
                        .HasColumnType("int");

                    b.Property<double>("Money")
                        .HasColumnType("float");

                    b.Property<int?>("Oplacheno")
                        .HasColumnType("int");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TabelCode");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("kz.Models.Setting", b =>
                {
                    b.Property<string>("TabelCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("APIkey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TabelCode");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("kz.Models.User", b =>
                {
                    b.Property<string>("TabelCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("APIkey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AfterDolg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BeforeDolg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalDohod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TabelCode");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
